# Generated by Django 4.2.3 on 2023-09-20 20:43

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=myapp.models.upload_to),
        ),
    ]
