# Generated by Django 3.2.21 on 2023-09-21 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.peoplegroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='EVent Image'),
            preserve_default=False,
        ),
    ]
