# Generated by Django 4.2.5 on 2023-09-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.event')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.image')),
            ],
            options={
                'db_table': 'event_thumbnail',
            },
        ),
        migrations.CreateModel(
            name='CommentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.comment')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.image')),
            ],
            options={
                'db_table': 'comment_images',
            },
        ),
    ]
