# Generated by Django 3.2.21 on 2023-09-22 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230921_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimages',
            name='image_id',
        ),
        migrations.AddField(
            model_name='commentimages',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='Event Image'),
        ),
        migrations.DeleteModel(
            name='EventThumbnail',
        ),
    ]
