# Generated by Django 3.2.21 on 2023-09-22 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230922_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
